steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/YOUR_PROJECT_ID/cloud-run-source-deploy/commingsoon/commingsoon:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/YOUR_PROJECT_ID/cloud-run-source-deploy/commingsoon/commingsoon:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'commingsoon'
  - '--image'
  - 'us-central1-docker.pkg.dev/YOUR_PROJECT_ID/cloud-run-source-deploy/commingsoon/commingsoon:$COMMIT_SHA'
  - '--region'
  - 'us-central1'

images:
- 'us-central1-docker.pkg.dev/YOUR_PROJECT_ID/cloud-run-source-deploy/commingsoon/commingsoon:$COMMIT_SHA'
